// Code generated by Supernova from Figma prototype

import 'package:flutter/material.dart';

import 'colors.dart';

class AppTextStyles {
  static const headerH1 = TextStyle(
    fontFamily: "Nunito Sans",
    fontWeight: FontWeight.w700,
    fontStyle: FontStyle.normal,
    fontSize: 36,
    decoration: TextDecoration.none,
    letterSpacing: 0.8999999999999999,
    color: AppColors.primaryDark,
  );

  static const headerH2 = TextStyle(
    fontFamily: "Nunito Sans",
    fontWeight: FontWeight.w400,
    fontStyle: FontStyle.normal,
    fontSize: 28,
    decoration: TextDecoration.none,
    letterSpacing: 0.7000000000000001,
    color: AppColors.primaryDark,
  );

  static const headerH3 = TextStyle(
    fontFamily: "Nunito Sans",
    fontWeight: FontWeight.w700,
    fontStyle: FontStyle.normal,
    fontSize: 26,
    decoration: TextDecoration.none,
    letterSpacing: 0,
    color: AppColors.primaryDark,
  );

  static const headerH4 = TextStyle(
    fontFamily: "Nunito Sans",
    fontWeight: FontWeight.w400,
    fontStyle: FontStyle.normal,
    fontSize: 20,
    decoration: TextDecoration.none,
    letterSpacing: 0,
    color: AppColors.primaryDark,
  );

  static const headerH5 = TextStyle(
    fontFamily: "Nunito Sans",
    fontWeight: FontWeight.w700,
    fontStyle: FontStyle.normal,
    fontSize: 18,
    decoration: TextDecoration.none,
    letterSpacing: 0.44999999999999996,
    color: AppColors.primaryDark,
  );

  static const paragraphText = TextStyle(
    fontFamily: "Nunito Sans",
    fontWeight: FontWeight.w400,
    fontStyle: FontStyle.normal,
    fontSize: 18,
    decoration: TextDecoration.none,
    letterSpacing: 1.08,
    color: AppColors.primaryDark,
  );

  static const paragraphSubtext = TextStyle(
    fontFamily: "Nunito Sans",
    fontWeight: FontWeight.w400,
    fontStyle: FontStyle.normal,
    fontSize: 14,
    decoration: TextDecoration.none,
    letterSpacing: 0.8400000000000001,
    color: AppColors.primaryDark,
  );

  static const cardTitle = TextStyle(
    fontFamily: "Nunito Sans",
    fontWeight: FontWeight.w700,
    fontStyle: FontStyle.normal,
    fontSize: 20,
    decoration: TextDecoration.none,
    letterSpacing: 0.5,
    color: AppColors.primaryDark,
  );

  static const cardSubtitle = TextStyle(
    fontFamily: "Nunito Sans",
    fontWeight: FontWeight.w400,
    fontStyle: FontStyle.normal,
    fontSize: 14,
    decoration: TextDecoration.none,
    letterSpacing: 0.35000000000000003,
    color: AppColors.primaryDark,
  );

  AppTextStyles._();
}

class KompasBodyText extends StatelessWidget {
  const KompasBodyText({
    Key? key,
    required this.text,
  }) : super(key: key);

  final String text;
  @override
  Widget build(BuildContext context) {
    return Text(
      text,
      softWrap: true,
      style: Theme.of(context).textTheme.bodyText2,
    );
  }
}

class KompasTitleText extends StatelessWidget {
  const KompasTitleText({
    Key? key,
    required this.text,
  }) : super(key: key);

  final String text;
  @override
  Widget build(BuildContext context) {
    return Text(
      text,
      style: Theme.of(context).textTheme.headline5,
    );
  }
}
