// Code generated by Supernova from Figma prototype

import 'package:flutter/material.dart';

class AppColors extends Color {
  /// Cutty Sark
  static const primaryNormal = Color(0xff57766e);

  static const primaryDark = Color(0xff18211f);

  static const primaryLight = Color(0xff96cbbd);

  /// Tint 90%
  static const primaryGray = Color(0xffcdd6d4);

  /// Tint 90%
  static const primaryWhite = Color(0xffeef1f1);

  static const selectionBlue = Color(0xff7fd6dd);

  static const selectionViolet = Color(0xffe5b6fc);

  static const selectionPink = Color(0xffffa2bf);

  static const selectionYellow = Color(0xfffbdd65);

  AppColors(int value) : super(value);
}
